// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using najlepsze_filmy.Data;

#nullable disable

namespace najlepsze_filmy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("najlepsze_filmy.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Akcja"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Komedia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dramat"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Romans"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Przygodowy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kryminał"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Dokumentalny"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Familijny"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Animacja"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Wojenny"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Historyczny"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Przyrodniczy"
                        });
                });

            modelBuilder.Entity("najlepsze_filmy.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "29-Maj-2022",
                            GenreId = 10,
                            Title = "Władca Pierścieni: Drużyna Pierścienia"
                        },
                        new
                        {
                            Id = 2,
                            Date = "29-Maj-2022",
                            GenreId = 10,
                            Title = "Władca Pierścieni: Dwie wieże"
                        },
                        new
                        {
                            Id = 3,
                            Date = "29-Maj-2022",
                            GenreId = 10,
                            Title = "Władca Pierścieni: Powrót króla"
                        },
                        new
                        {
                            Id = 4,
                            Date = "11-Styczeń-2022",
                            GenreId = 4,
                            Title = "Obecność"
                        },
                        new
                        {
                            Id = 5,
                            Date = "20-Styczeń-2022",
                            GenreId = 10,
                            Title = "Fantastyczne zwierzęta: Tajemnice Dumbledore’a"
                        },
                        new
                        {
                            Id = 6,
                            Date = "22-Luty-2022",
                            GenreId = 1,
                            Title = "Uncharted"
                        },
                        new
                        {
                            Id = 7,
                            Date = "01-Marzec-2022",
                            GenreId = 6,
                            Title = "Piraci z Karaibów: Skrzynia umarlaka"
                        },
                        new
                        {
                            Id = 8,
                            Date = "11-Marzec-2022",
                            GenreId = 4,
                            Title = "Annabelle"
                        },
                        new
                        {
                            Id = 9,
                            Date = "18-Marzec-2022",
                            GenreId = 3,
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 10,
                            Date = "24-Kwiecień-2022",
                            GenreId = 1,
                            Title = "Szybcy i wściekli 9"
                        },
                        new
                        {
                            Id = 11,
                            Date = "24-Kwiecień-2022",
                            GenreId = 10,
                            Title = "Fantastyczne zwierzęta: Zbrodnie Grindelwalda"
                        },
                        new
                        {
                            Id = 12,
                            Date = "06-Maj-2022",
                            GenreId = 1,
                            Title = "Top Gun: Maverick"
                        },
                        new
                        {
                            Id = 13,
                            Date = "21-Grudzień-2022",
                            GenreId = 10,
                            Title = "Hobbit: Niezwykła podróż"
                        },
                        new
                        {
                            Id = 14,
                            Date = "22-Grudzień-2022",
                            GenreId = 10,
                            Title = "Hobbit: Pustkowie Smauga"
                        },
                        new
                        {
                            Id = 15,
                            Date = "23-Grudzień-2022",
                            GenreId = 10,
                            Title = "Hobbit: Bitwa Pięciu Armii"
                        },
                        new
                        {
                            Id = 16,
                            Date = "27-Listopad-2022",
                            GenreId = 6,
                            Title = "King Kong"
                        },
                        new
                        {
                            Id = 17,
                            Date = "02-Wrzesień-2022",
                            GenreId = 8,
                            Title = "Zabójcze maszyny"
                        },
                        new
                        {
                            Id = 18,
                            Date = "15-Wrzesień-2022",
                            GenreId = 6,
                            Title = "Przygody Tintina"
                        },
                        new
                        {
                            Id = 19,
                            Date = "14-Czerwiec-2022",
                            GenreId = 1,
                            Title = "Strażnicy Galaktyki"
                        },
                        new
                        {
                            Id = 20,
                            Date = "19-Czerwiec-2022",
                            GenreId = 10,
                            Title = "Warcraft: Początek"
                        },
                        new
                        {
                            Id = 21,
                            Date = "20-Czerwiec-2022",
                            GenreId = 1,
                            Title = "Thor: Ragnarok"
                        },
                        new
                        {
                            Id = 22,
                            Date = "14-Lipiec-2022",
                            GenreId = 8,
                            Title = "Ewolucja planety małp"
                        },
                        new
                        {
                            Id = 23,
                            Date = "14-Sierpień-2022",
                            GenreId = 8,
                            Title = "Wojna o planetę małp"
                        },
                        new
                        {
                            Id = 24,
                            Date = "20-Sierpień-2022",
                            GenreId = 1,
                            Title = "Doktor Strange"
                        },
                        new
                        {
                            Id = 25,
                            Date = "14-Październik-2022",
                            GenreId = 3,
                            Title = "Życie jest piękne"
                        },
                        new
                        {
                            Id = 26,
                            Date = "29-Styczeń-2022",
                            GenreId = 3,
                            Title = "Green Book"
                        },
                        new
                        {
                            Id = 27,
                            Date = "03-Listopad-2022",
                            GenreId = 2,
                            Title = "Free Guy"
                        },
                        new
                        {
                            Id = 28,
                            Date = "14-Listopad-2022",
                            GenreId = 6,
                            Title = "Wyprawa do dżungli"
                        },
                        new
                        {
                            Id = 29,
                            Date = "22-Kwiecień-2022",
                            GenreId = 6,
                            Title = "Doktor Dolittle"
                        },
                        new
                        {
                            Id = 30,
                            Date = "17-Wrzesień-2022",
                            GenreId = 1,
                            Title = "Venom 2: Carnage"
                        },
                        new
                        {
                            Id = 31,
                            Date = "19-Lipiec-2022",
                            GenreId = 2,
                            Title = "Wasza wysokość"
                        },
                        new
                        {
                            Id = 32,
                            Date = "20-lipiec-2022",
                            GenreId = 2,
                            Title = "Noc w muzeum: Tajemnica grobowca"
                        },
                        new
                        {
                            Id = 33,
                            Date = "21-Lipiec-2022",
                            GenreId = 1,
                            Title = "Raya i ostatni smok"
                        },
                        new
                        {
                            Id = 34,
                            Date = "22-Lipiec-2022",
                            GenreId = 12,
                            Title = "Clifford. Wielki czerwony pies"
                        },
                        new
                        {
                            Id = 35,
                            Date = "23-Lipiec-2022",
                            GenreId = 12,
                            Title = "Fernando"
                        },
                        new
                        {
                            Id = 36,
                            Date = "24-Lipiec-2022",
                            GenreId = 14,
                            Title = "Dunkierka"
                        },
                        new
                        {
                            Id = 37,
                            Date = "25-Lipiec-2022",
                            GenreId = 14,
                            Title = "1917"
                        },
                        new
                        {
                            Id = 38,
                            Date = "26-Lipiec-2022",
                            GenreId = 11,
                            Title = "Sól ziemi"
                        },
                        new
                        {
                            Id = 39,
                            Date = "27-Lipiec-2022",
                            GenreId = 11,
                            Title = "Pina"
                        },
                        new
                        {
                            Id = 40,
                            Date = "08-Luty-2022",
                            GenreId = 5,
                            Title = "Wredne igraszki"
                        },
                        new
                        {
                            Id = 41,
                            Date = "10-Luty-2022",
                            GenreId = 3,
                            Title = "CODA"
                        },
                        new
                        {
                            Id = 42,
                            Date = "14-Lipiec-2022",
                            GenreId = 15,
                            Title = "Kopciuszek"
                        },
                        new
                        {
                            Id = 43,
                            Date = "11-Lipiec-2022",
                            GenreId = 2,
                            Title = "Książę w Nowym Jorku 2"
                        },
                        new
                        {
                            Id = 44,
                            Date = "23-Luty-2022",
                            GenreId = 5,
                            Title = "Wieczny singiel"
                        },
                        new
                        {
                            Id = 45,
                            Date = "01-Grudzień-2022",
                            GenreId = 1,
                            Title = "Nie czas umierać"
                        },
                        new
                        {
                            Id = 46,
                            Date = "15-Czerwiec-2022",
                            GenreId = 3,
                            Title = "Czarnobyl 1986"
                        },
                        new
                        {
                            Id = 47,
                            Date = "11-Październik-2022",
                            GenreId = 3,
                            Title = "Sightless"
                        },
                        new
                        {
                            Id = 48,
                            Date = "04-Październik-2022",
                            GenreId = 4,
                            Title = "Brahms: The Boy II"
                        },
                        new
                        {
                            Id = 49,
                            Date = "17-Lipiec-2022",
                            GenreId = 11,
                            Title = "Kiss the Ground"
                        },
                        new
                        {
                            Id = 50,
                            Date = "10-Lipiec-2022",
                            GenreId = 17,
                            Title = "Ośmiornica, nauczycielka życia"
                        },
                        new
                        {
                            Id = 51,
                            Date = "26-Grudzień-2022",
                            GenreId = 6,
                            Title = "Czarna Wdowa"
                        },
                        new
                        {
                            Id = 52,
                            Date = "25-Lipiec-2022",
                            GenreId = 6,
                            Title = "Legion samobójców: The Suicide Squad"
                        },
                        new
                        {
                            Id = 53,
                            Date = "26-Maj-2022",
                            GenreId = 6,
                            Title = "Spider-Man: Bez drogi do domu"
                        });
                });

            modelBuilder.Entity("najlepsze_filmy.Models.MovieRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RatingId");

                    b.ToTable("MovieRatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 1,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 2,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 2,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 3,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 3,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 4,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 4,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 4,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 5,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 5,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 5,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 6,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 6,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 6,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 7,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 7,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 7,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 8,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 8,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 8,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 9,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 9,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 10,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 10,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 30,
                            MovieId = 11,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 31,
                            MovieId = 11,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 32,
                            MovieId = 12,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 33,
                            MovieId = 12,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 34,
                            MovieId = 12,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 35,
                            MovieId = 12,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 36,
                            MovieId = 12,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 37,
                            MovieId = 13,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 38,
                            MovieId = 13,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 39,
                            MovieId = 14,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 40,
                            MovieId = 15,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 41,
                            MovieId = 15,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 42,
                            MovieId = 16,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 43,
                            MovieId = 16,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 44,
                            MovieId = 16,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 45,
                            MovieId = 17,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 46,
                            MovieId = 18,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 47,
                            MovieId = 18,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 48,
                            MovieId = 19,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 49,
                            MovieId = 19,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 50,
                            MovieId = 19,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 51,
                            MovieId = 20,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 52,
                            MovieId = 20,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 53,
                            MovieId = 21,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 54,
                            MovieId = 22,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 55,
                            MovieId = 23,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 56,
                            MovieId = 24,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 57,
                            MovieId = 25,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 58,
                            MovieId = 25,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 59,
                            MovieId = 26,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 60,
                            MovieId = 26,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 61,
                            MovieId = 27,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 62,
                            MovieId = 27,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 63,
                            MovieId = 28,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 64,
                            MovieId = 29,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 65,
                            MovieId = 30,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 66,
                            MovieId = 30,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 67,
                            MovieId = 30,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 68,
                            MovieId = 31,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 69,
                            MovieId = 31,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 70,
                            MovieId = 31,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 71,
                            MovieId = 32,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 72,
                            MovieId = 32,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 73,
                            MovieId = 33,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 74,
                            MovieId = 33,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 75,
                            MovieId = 33,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 76,
                            MovieId = 34,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 77,
                            MovieId = 35,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 78,
                            MovieId = 35,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 79,
                            MovieId = 35,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 80,
                            MovieId = 35,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 81,
                            MovieId = 35,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 82,
                            MovieId = 36,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 83,
                            MovieId = 36,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 84,
                            MovieId = 36,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 85,
                            MovieId = 36,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 86,
                            MovieId = 36,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 87,
                            MovieId = 37,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 88,
                            MovieId = 37,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 89,
                            MovieId = 37,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 90,
                            MovieId = 38,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 91,
                            MovieId = 38,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 92,
                            MovieId = 38,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 93,
                            MovieId = 39,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 94,
                            MovieId = 39,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 95,
                            MovieId = 39,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 96,
                            MovieId = 39,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 97,
                            MovieId = 40,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 98,
                            MovieId = 40,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 99,
                            MovieId = 40,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 100,
                            MovieId = 40,
                            RatingId = 2
                        },
                        new
                        {
                            Id = 101,
                            MovieId = 41,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 102,
                            MovieId = 41,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 103,
                            MovieId = 41,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 104,
                            MovieId = 41,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 105,
                            MovieId = 41,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 106,
                            MovieId = 41,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 107,
                            MovieId = 43,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 108,
                            MovieId = 43,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 109,
                            MovieId = 43,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 110,
                            MovieId = 44,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 111,
                            MovieId = 45,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 112,
                            MovieId = 45,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 113,
                            MovieId = 45,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 114,
                            MovieId = 45,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 115,
                            MovieId = 45,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 116,
                            MovieId = 45,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 117,
                            MovieId = 47,
                            RatingId = 3
                        },
                        new
                        {
                            Id = 118,
                            MovieId = 47,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 119,
                            MovieId = 48,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 120,
                            MovieId = 48,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 121,
                            MovieId = 48,
                            RatingId = 4
                        },
                        new
                        {
                            Id = 122,
                            MovieId = 49,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 123,
                            MovieId = 51,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 124,
                            MovieId = 51,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 126,
                            MovieId = 52,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 127,
                            MovieId = 52,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 128,
                            MovieId = 52,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 129,
                            MovieId = 52,
                            RatingId = 1
                        },
                        new
                        {
                            Id = 130,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 131,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 132,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 133,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 134,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 135,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 136,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 137,
                            MovieId = 53,
                            RatingId = 5
                        },
                        new
                        {
                            Id = 138,
                            MovieId = 53,
                            RatingId = 5
                        });
                });

            modelBuilder.Entity("najlepsze_filmy.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Niedostateczna"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dopuszczająca"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dostateczna"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dobra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bardzo dobra"
                        });
                });

            modelBuilder.Entity("najlepsze_filmy.Models.Movie", b =>
                {
                    b.HasOne("najlepsze_filmy.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("najlepsze_filmy.Models.MovieRating", b =>
                {
                    b.HasOne("najlepsze_filmy.Models.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("najlepsze_filmy.Models.Rating", "Rating")
                        .WithMany("MovieRatings")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("najlepsze_filmy.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("najlepsze_filmy.Models.Movie", b =>
                {
                    b.Navigation("MovieRatings");
                });

            modelBuilder.Entity("najlepsze_filmy.Models.Rating", b =>
                {
                    b.Navigation("MovieRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
